<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Book Now</name>
   <tag></tag>
   <elementGuidId>1334e1c7-68d0-425b-9c53-b2f26ef5add1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.fw-bold.w-100.waves-effect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d93df306-fa2a-45a6-908e-baa18c3fe707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a9bf1314-ba90-46fd-b5d4-5aa356143930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary fw-bold w-100 waves-effect</value>
      <webElementGuid>ee63f2da-363d-4f8d-87a4-39e3e828312d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book Now</value>
      <webElementGuid>3664857d-4eee-4a2b-9cf6-2e4a2b5e72b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/div[@class=&quot;bg-light pt-4&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row gx-0 gy-3 bg-white rounded-2 overflow-hidden mt-3 px-3 pb-3&quot;]/div[@class=&quot;col-xl-10 col-md-12 col-12 px-xl-4 px-lg-0&quot;]/div[@class=&quot;mt-sm-3 mt-md-0&quot;]/form[1]/div[@class=&quot;row g-0&quot;]/div[@class=&quot;order-2 order-sm-3 col-6 col-xl-5 col-lg-6 col-md-6 border border-top-0 p-3&quot;]/div[@class=&quot;d-flex justify-content-center align-items-center h-100&quot;]/div[@class=&quot;col-xl-5 col-lg-5 col-md-12 col-12 ps-sm-3 mb-2 mb-md-0 text-center&quot;]/div[1]/button[@class=&quot;btn btn-primary fw-bold w-100 waves-effect&quot;]</value>
      <webElementGuid>db8ed12a-6821-4d8d-a1b1-a1aafc7c11f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>aadb76a2-d5f9-4d89-ab1a-600831deeda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div/div/div[3]/div[3]/div[2]/form/div/div[4]/div/div/div/button</value>
      <webElementGuid>c92ef849-579a-42da-b2f2-05f59dfe5e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[3]/following::button[1]</value>
      <webElementGuid>bf7eefdd-bafc-4da2-963f-75b0d0478882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collection Of Flat Icon, Symbols And Glyph Icons'])[1]/following::button[1]</value>
      <webElementGuid>971be31c-c708-4608-84d0-a497c15c0f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Three Bedroom Apartment'])[1]/preceding::button[1]</value>
      <webElementGuid>346af880-b034-4f85-9fa6-e94a4aec2b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[2]/preceding::button[1]</value>
      <webElementGuid>08f937ee-d093-4678-84e4-f4217dcd1b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Book Now']/parent::*</value>
      <webElementGuid>baf782c8-d69b-4322-86fb-9f4ec66eb0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>e217e2fe-1578-4991-b2b7-d13062030e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Book Now' or . = 'Book Now')]</value>
      <webElementGuid>1d039077-b2eb-4c75-8634-0bd1d8f1538f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
