<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done</name>
   <tag></tag>
   <elementGuidId>75310921-b4ef-4fad-8182-3c64e65361c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ui-datepicker-close.ui-state-default.ui-priority-primary.ui-corner-all.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4415dcbf-01d6-48f7-8a2b-bfe244c74d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>741f54bf-4a8d-47c0-a0b4-03e5b74a692d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-close ui-state-default ui-priority-primary ui-corner-all ui-state-hover</value>
      <webElementGuid>2b04c608-5a4c-482a-8945-4c21d06e3710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler</name>
      <type>Main</type>
      <value>hide</value>
      <webElementGuid>94b9bd7c-049a-4027-9682-3f5f2df03b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>15543ea8-fe8c-4ebf-8f8f-f142c38ea72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>257d3e87-313b-418b-932f-6106214ecd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/div[@class=&quot;ui-datepicker-buttonpane ui-widget-content&quot;]/button[@class=&quot;ui-datepicker-close ui-state-default ui-priority-primary ui-corner-all ui-state-hover&quot;]</value>
      <webElementGuid>2c681684-b107-4793-b5c0-721c281c198a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>1132f7cd-f34b-47ef-a67a-3a17e7085f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/div[3]/button[2]</value>
      <webElementGuid>203ac35d-e1ef-45fd-8d33-39b8f7935c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Now'])[1]/following::button[1]</value>
      <webElementGuid>bb0ed171-9072-47cc-80dd-0cfa624dcf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Zone'])[1]/following::button[2]</value>
      <webElementGuid>3f66fcd2-f1aa-4a49-bd42-6ee7703b4dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>e302cdfe-0d3c-419c-9f98-7733b35b1001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>50660597-2fbb-4c9f-a338-0203c3f0b395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>1cbc15eb-44e0-4085-9250-51aae0ebd9ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
