<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_000000</name>
   <tag></tag>
   <elementGuidId>9c6b5aca-2e90-4cd4-b924-d528a69f9c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>dd.ui_tpicker_time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-datepicker-div']/div[2]/dl/dd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dd</value>
      <webElementGuid>0e326f60-769a-4e28-a231-7c3b98366d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui_tpicker_time</value>
      <webElementGuid>e60ee8ed-49e6-45c5-9a73-8fa866bc046b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00:00:00</value>
      <webElementGuid>78c3b3a0-da5b-4a0a-81ee-3cac2448c09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/div[@class=&quot;ui-timepicker-div&quot;]/dl[1]/dd[@class=&quot;ui_tpicker_time&quot;]</value>
      <webElementGuid>6307fbaf-5091-44c3-9187-4f723592618b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/div[2]/dl/dd</value>
      <webElementGuid>43cdacfd-4f9e-4cb3-9b02-ce25b1401cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/following::dd[1]</value>
      <webElementGuid>36d7885e-c9a4-4946-85b0-5d9ae3d92019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Time'])[1]/following::dd[1]</value>
      <webElementGuid>fe65d885-bc47-4fc4-bc8d-a4ed9c5119d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hour'])[1]/preceding::dd[1]</value>
      <webElementGuid>ed0fdcd1-9e16-499d-b94e-7c84a1514848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minute'])[1]/preceding::dd[2]</value>
      <webElementGuid>89422799-4da1-46f0-81d2-de42e6143dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='00:00:00']/parent::*</value>
      <webElementGuid>bda379c9-611b-4553-bfcd-7b67d6204fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd</value>
      <webElementGuid>91270442-9762-477f-aebc-e23b3e179cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dd[(text() = '00:00:00' or . = '00:00:00')]</value>
      <webElementGuid>4f8a0500-1c5d-4a54-9abb-2b764b64ca6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
