<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Arrival Time_ZmxpZ2h0cy5hcnJpdmFsX3RpbWU-</name>
   <tag></tag>
   <elementGuidId>1da184da-16da-4ee8-9e00-2d62a6f0a391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1688128550858</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp1688128550858']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d789e7d-be4d-4784-bfec-ed763bad9f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-input xcrud-datepicker form-control hasDatepicker</value>
      <webElementGuid>04e688f2-5c1a-4397-92d3-6f1b4c43d801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f78dd2a-fd66-4a1d-bf74-aa459f40b651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>3fcd285d-10e9-456e-9537-f58aeb30c34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ZmxpZ2h0cy5hcnJpdmFsX3RpbWU-</value>
      <webElementGuid>d4392843-286d-4e33-8548-8de68c98c5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1688128550858</value>
      <webElementGuid>e84be280-9a69-45e8-b15f-feae58732479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1688128550858&quot;)</value>
      <webElementGuid>b812bd97-43c5-459b-b603-bbd7e7088399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1688128550858']</value>
      <webElementGuid>730ed297-7eec-4d55-b51d-9161638efd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/input</value>
      <webElementGuid>2b174523-159a-451b-a776-e2d33fb52be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ZmxpZ2h0cy5hcnJpdmFsX3RpbWU-' and @id = 'dp1688128550858']</value>
      <webElementGuid>7ef3f65e-21f5-4885-b7e7-eb7b6226580c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
