<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adult Seat Price_ZmxpZ2h0cy5hZHVsdF9z_72cb70</name>
   <tag></tag>
   <elementGuidId>c0679ac5-e7f6-4b5d-ac35-ec082ac2874e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ZmxpZ2h0cy5hZHVsdF9zZWF0X3ByaWNl&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ZmxpZ2h0cy5hZHVsdF9zZWF0X3ByaWNl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>787ae4b1-f4d3-4601-8bc3-f46294b60a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-input form-control</value>
      <webElementGuid>5ded03d7-e506-462a-a93d-683fcc91c526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8097e42-3a08-4135-a12d-07a2b10defb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>int</value>
      <webElementGuid>1be9d33f-d553-4bda-90fb-27e8d4cdec51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e663c16-9bbf-4fd0-9946-e53d1126265e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ZmxpZ2h0cy5hZHVsdF9zZWF0X3ByaWNl</value>
      <webElementGuid>ab2bd965-8b58-4236-83ab-11f2c1d6676a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>a7266ce2-edb3-4f2d-8ae2-6b6ae345286e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>29e394f8-eafb-4203-b157-2210b6cb9752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;w-100&quot;]/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;xcrud&quot;]/div[@class=&quot;xcrud-container&quot;]/div[@class=&quot;xcrud-ajax&quot;]/div[@class=&quot;xcrud-view&quot;]/table[@class=&quot;form-horizontal&quot;]/tbody[1]/tr[@class=&quot;mb-1 row&quot;]/td[@class=&quot;col-md-6&quot;]/input[@class=&quot;xcrud-input form-control&quot;]</value>
      <webElementGuid>c3e9f249-66f6-44c2-9e6c-f7c170379308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ZmxpZ2h0cy5hZHVsdF9zZWF0X3ByaWNl']</value>
      <webElementGuid>b721aa5c-1f60-44bd-9c85-da72c1fed3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>9008550f-b0d8-4851-970c-861082ed4a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ZmxpZ2h0cy5hZHVsdF9zZWF0X3ByaWNl']</value>
      <webElementGuid>22f0dca8-eb4f-462d-b3b0-24b8c5d5ece4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
