<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_child price_ZmxpZ2h0cy5jaGlsZF9zZWF0X3ByaWNl</name>
   <tag></tag>
   <elementGuidId>5110e5ab-cea2-4e1c-9dfd-e7c1a3546642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ZmxpZ2h0cy5jaGlsZF9zZWF0X3ByaWNl&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ZmxpZ2h0cy5jaGlsZF9zZWF0X3ByaWNl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e85c48f1-0c97-46eb-9c8c-2f2820b5dec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-input form-control</value>
      <webElementGuid>7ede6512-dfe3-4408-b6d7-f1862e8285b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a470154-7077-449a-946b-4a15be56f565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>int</value>
      <webElementGuid>096d1c3e-a5c4-4131-bfd1-206fd27e7459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>60437683-2cfb-4e13-ac36-a768ad76b679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ZmxpZ2h0cy5jaGlsZF9zZWF0X3ByaWNl</value>
      <webElementGuid>74687c2e-e581-472d-ab6f-c8ffe5d7188a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>ca0776e2-7ccb-4e43-b5f7-36e8a116673e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>f8f8adad-0fea-49d5-9647-630e4ae7ce90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/section[@class=&quot;w-100&quot;]/div[@class=&quot;container mt-3&quot;]/div[@class=&quot;xcrud&quot;]/div[@class=&quot;xcrud-container&quot;]/div[@class=&quot;xcrud-ajax&quot;]/div[@class=&quot;xcrud-view&quot;]/table[@class=&quot;form-horizontal&quot;]/tbody[1]/tr[@class=&quot;mb-1 row&quot;]/td[@class=&quot;col-md-6&quot;]/input[@class=&quot;xcrud-input form-control&quot;]</value>
      <webElementGuid>1ffb1df7-4bdc-4863-845b-3fa4d63b3960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ZmxpZ2h0cy5jaGlsZF9zZWF0X3ByaWNl']</value>
      <webElementGuid>769c7d6c-2bac-4daf-a74a-a696aea5e94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>bc10b9af-784b-4615-82b8-4817c67244b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ZmxpZ2h0cy5jaGlsZF9zZWF0X3ByaWNl']</value>
      <webElementGuid>c69f371e-2aba-4b8f-97e1-c288c22f56dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
