<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Departure Time_ZmxpZ2h0cy5kZXBhcnR1cm_c33765</name>
   <tag></tag>
   <elementGuidId>c600f77a-9034-4bf4-b7bc-c184eed850e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1688128550857</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp1688128550857']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c587efa7-f6a3-4568-a793-0b2d187195b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcrud-input xcrud-datepicker form-control hasDatepicker</value>
      <webElementGuid>aa216aaa-9044-4634-b566-d0a348435cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99fb53ae-2c72-4419-aa56-4a560a005c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>a5555d09-2996-44b8-9fef-2681fbafd87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ZmxpZ2h0cy5kZXBhcnR1cmVfdGltZQ--</value>
      <webElementGuid>99ff943f-4cd6-48a7-93e4-a3dace550ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1688128550857</value>
      <webElementGuid>134b3835-e66f-4930-9030-a3ef8efa3930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1688128550857&quot;)</value>
      <webElementGuid>20021d26-562d-432c-af70-86bfad0e9aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1688128550857']</value>
      <webElementGuid>b7db0eeb-fd9b-408d-a17a-c986bad6d968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/input</value>
      <webElementGuid>cf27395e-48e0-43ef-9693-4064ee28d5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ZmxpZ2h0cy5kZXBhcnR1cmVfdGltZQ--' and @id = 'dp1688128550857']</value>
      <webElementGuid>86e01d21-2633-4111-a02e-8b8470c9fc8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
