<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PayPal_form</name>
   <tag></tag>
   <elementGuidId>156be18f-f2d6-4ae7-ba31-bd1e753c80d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9142cbf0-75f3-43b5-b530-e10d2d67bdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>4b63fec6-6c38-4d50-aa88-b8e883ad366f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e663a530-2c2b-4fb1-8caf-26031cc2b901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success w-100</value>
      <webElementGuid>ad22eaad-58fb-4389-9a99-4c91f6f0d870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Proceed</value>
      <webElementGuid>4c0a27e4-84ee-48b1-8650-2266eef34832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)</value>
      <webElementGuid>9911ec3c-61c9-4ade-b547-6d529ef8fb23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form']</value>
      <webElementGuid>abafb341-381e-4293-874e-83e2f0ed813c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_gateway']/div/div[3]/input[2]</value>
      <webElementGuid>dbb0aed2-180c-4ea9-8f9e-48aa70e2d764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>14ffeab5-8e0b-4f2b-866c-6c3de0009cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form' and @type = 'submit']</value>
      <webElementGuid>719517aa-7078-4dfb-87c4-710c87521c86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
