<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Indonesia_1</name>
   <tag></tag>
   <elementGuidId>481f0c98-7276-4559-ba43-1e87963375bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-2-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-2-100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90583fbb-9789-480c-af2b-17c15475c983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b27c2179-2869-4173-a848-6603c5925f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>6c89b96f-f517-498f-bcc8-519b21a7ba67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bs-select-2-100</value>
      <webElementGuid>3acbf87c-bc9d-41e0-a633-425960bfa4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab72808d-fc64-4378-9deb-d1f8be02e281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>fce2fcc2-a62d-406e-920a-72609a1120bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>101</value>
      <webElementGuid>bbd212b1-0b74-46ab-ad73-d31a868f9103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Indonesia 
                            </value>
      <webElementGuid>d9cc0dc4-2d9d-4903-b59f-743637f1554b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-2-100&quot;)</value>
      <webElementGuid>474ddbc2-5171-44e0-99ea-7b9498b74849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bs-select-2-100']</value>
      <webElementGuid>8c3b8b8b-3b20-41c9-9b42-fa2c6e8785aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-select-2']/ul/li[101]/a</value>
      <webElementGuid>d69ccca2-5cb5-4fbd-94cf-b8f8969fd363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[2]/following::a[1]</value>
      <webElementGuid>0bea1fc4-80f9-486f-a740-764792d1ebb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iceland'])[2]/following::a[2]</value>
      <webElementGuid>43e2e55b-3860-4aeb-b44e-016e6abe2bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iran, Islamic Republic of'])[2]/preceding::a[1]</value>
      <webElementGuid>34eb3ef6-8d43-463e-9249-8dc6a39c2706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]/ul/li[101]/a</value>
      <webElementGuid>a024b9f2-7198-4042-ac6a-26a9b124f1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bs-select-2-100' and (text() = ' Indonesia 
                            ' or . = ' Indonesia 
                            ')]</value>
      <webElementGuid>0edcf7e8-b9ca-4447-b662-48bd3e621b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
