<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Indonesia</name>
   <tag></tag>
   <elementGuidId>60c6d6b1-44fd-4ab0-a6fb-df2ee443a281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-1-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-1-100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5e2e5ac-9092-446a-b1e1-0f9b08fb574f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5bad5abc-2fd6-4bed-ad2c-3d98da9cd953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>61abe482-70b3-4865-829a-7a31565fd010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bs-select-1-100</value>
      <webElementGuid>d0ff5559-347f-4d5d-a3cb-b9dcbcf192db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2c89189d-9acf-42ee-ad93-29afda66f2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>0081b604-d0d8-4452-aeea-c7b394e519b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>101</value>
      <webElementGuid>0d23baf0-c4d0-4c00-8e7c-973519a275f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Indonesia </value>
      <webElementGuid>c3d33da9-8682-4642-b56c-81e34d5adfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-1-100&quot;)</value>
      <webElementGuid>a0e6c0f1-164d-4406-816d-98e3c8ad1e24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bs-select-1-100']</value>
      <webElementGuid>2ede7178-58f5-4529-a01e-5675c9442f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-select-1']/ul/li[101]/a</value>
      <webElementGuid>82e0eddc-96e9-4d05-84f3-b16717b0fa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/following::a[1]</value>
      <webElementGuid>9b1667ca-f65d-4847-a785-be7a87a778e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iceland'])[1]/following::a[2]</value>
      <webElementGuid>dd5227d8-c0ae-4005-a34a-11c4ef792481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iran, Islamic Republic of'])[1]/preceding::a[1]</value>
      <webElementGuid>7c0023af-5e4c-498d-9b5a-91d13cba4f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[101]/a</value>
      <webElementGuid>8f8b6417-749b-4510-a87d-afb698c525a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bs-select-1-100' and (text() = ' Indonesia ' or . = ' Indonesia ')]</value>
      <webElementGuid>b32cb12d-b45e-4974-a836-6f19971592bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
