<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm Booking</name>
   <tag></tag>
   <elementGuidId>73cef137-f2e0-46aa-9a4d-05f8002f7427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#booking</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='booking']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>641e0e27-4e33-45c3-8fa2-ddad9ebb0970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary w-100 btn-lg book waves-effect</value>
      <webElementGuid>fe6e0f60-0f97-475e-b4ac-ffafd15a5462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c4c51f04-b77a-46c3-bada-b530d5efb992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>booking</value>
      <webElementGuid>199f9900-527a-4274-870d-82c0f10d45be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Confirm Booking</value>
      <webElementGuid>a84c739c-3389-4d9c-aa9a-8360646d5e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking&quot;)</value>
      <webElementGuid>7b9a9102-a640-4015-9199-eac33d8da85b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='booking']</value>
      <webElementGuid>393a779e-c577-457c-8c94-ded6385d97d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div[2]/form/section/div/div/div/div[6]/div/button</value>
      <webElementGuid>95adf935-44b5-486c-88f3-fbdbdc53547c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking Details'])[1]/preceding::button[1]</value>
      <webElementGuid>de9ea013-3788-472e-8196-c5e039b8ec65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movenpick Grand Al Bustan'])[1]/preceding::button[1]</value>
      <webElementGuid>0849a3f4-7ff5-4781-a6d7-2de8bfc38457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm Booking']/parent::*</value>
      <webElementGuid>e19589af-d5f6-4b5d-884d-4193a756fbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button</value>
      <webElementGuid>0c996b4e-4486-47ed-bcdd-2003e75f3547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'booking' and (text() = ' Confirm Booking' or . = ' Confirm Booking')]</value>
      <webElementGuid>58c3cc2e-a9bd-400b-8d3b-b30d459588dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
