<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Age_child_firstname_2</name>
   <tag></tag>
   <elementGuidId>8534ca12-8a46-456c-b6b3-7ebda08335ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;child_firstname_2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='child_firstname_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56f95c7e-17e0-44ae-a84b-df824921257c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>146adbff-3a97-4747-9e3c-7de29fb66b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>child_firstname_2</value>
      <webElementGuid>998ef614-b419-467d-a8f9-1e306647f75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4cef9837-4dc2-4269-b2d2-33b8349e6674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>1a6701d7-0ef1-4505-8701-bac6542839e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/div[@class=&quot;booking_data&quot;]/form[@class=&quot;book&quot;]/section[@class=&quot;booking-area padding-top-50px padding-bottom-70px&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;form-box payment-received-wrap mb-2&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;card mb-3&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;form-floating&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3b15d8b6-7772-4818-ab6d-c488fb0cd054</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='child_firstname_2']</value>
      <webElementGuid>d4a3f91d-29d3-4df7-9153-52d518506526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div[2]/form/section/div/div/div/div[2]/div[2]/div[4]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>a536b569-15a7-48f1-a62f-4b3ed82662a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>3fd1fc58-6b51-4eb4-b50c-15d382859c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'child_firstname_2' and @placeholder = 'First Name']</value>
      <webElementGuid>afb01c76-8e90-4e84-bbaf-b09ff6e2adde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
