<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Read Less_agreechb</name>
   <tag></tag>
   <elementGuidId>35a97484-d014-412d-9db2-7ed2ca50996e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agreechb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agreechb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96bb7ccd-c6fb-40ef-bc38-c951d14938c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f6bd8b91-7407-4066-8551-61835c7ce946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>45e4d515-bb42-48e3-981a-2b22ae8e8c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agreechb</value>
      <webElementGuid>25a960cd-df47-44b1-8041-564f105991c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('booking').disabled = !this.checked;</value>
      <webElementGuid>5064ff10-4264-4cd5-9bb4-bd45127d3bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agreechb&quot;)</value>
      <webElementGuid>546aa945-d2c5-4afd-8058-e7a0a3b18568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agreechb']</value>
      <webElementGuid>b4255bba-c98e-46a9-987e-b7c97736ba3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div[2]/form/section/div/div/div/div[5]/div/div/div/input</value>
      <webElementGuid>85dd5f8c-915f-40ac-b1b6-6bb129116a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>3e560c93-06fc-4910-ba06-cbf96646b065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'agreechb']</value>
      <webElementGuid>84f8d431-5752-43bb-9159-7d56260662a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
