<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment Methods_payment_gateway</name>
   <tag></tag>
   <elementGuidId>c09b6535-d6a3-4a92-8c91-fba674b77b39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gateway_paypal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gateway_paypal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93e5bd6f-8542-41e8-bf97-eca94fda98aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input mx-auto</value>
      <webElementGuid>0ce5539f-bd80-492b-9a6b-a860ccc210fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e25d5ec5-7a78-4e43-a664-34cd471ebd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_gateway</value>
      <webElementGuid>a01d1440-4c78-408a-a874-2418319ca5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gateway_paypal</value>
      <webElementGuid>deea179b-c84b-4bf9-9a08-a4977ae703aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>paypal</value>
      <webElementGuid>bd2ebbbe-b3d7-4f65-bbd2-21af75d58f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gateway_paypal&quot;)</value>
      <webElementGuid>757fa712-3028-4e19-a821-6d3c5ec74378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gateway_paypal']</value>
      <webElementGuid>798b4e1c-487c-49c8-a438-42e2e92871fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pills-home-tab']/div/input</value>
      <webElementGuid>ab8c2d4a-f110-453e-b9a7-ce2eb3e8bd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div/div/input</value>
      <webElementGuid>ab8441bd-9e21-4d94-aabb-16209476a4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'payment_gateway' and @id = 'gateway_paypal']</value>
      <webElementGuid>6eb3a5f3-9739-4772-8108-736a14f1efe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
