<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_useremail</name>
   <tag></tag>
   <elementGuidId>0fcf3864-1bb9-4a52-ba2b-b31867e643db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;user[email]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='user[email]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e35dd93b-94ac-402a-983e-5c9a21ab5a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c46ab31c-9651-4a97-ba34-6658de5cf20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[email]</value>
      <webElementGuid>58d8f9c7-d32d-41cc-83bf-5f3df05c79de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control</value>
      <webElementGuid>115fb885-4afe-4836-8e2b-d311f28d97f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>61f46419-2b77-4253-84e3-69ce39141a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/div[@class=&quot;booking_data&quot;]/form[@class=&quot;book&quot;]/section[@class=&quot;booking-area padding-top-50px padding-bottom-70px&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;form-box mb-2&quot;]/div[@class=&quot;form-content&quot;]/div[@class=&quot;contact-form-action&quot;]/div[@class=&quot;row g-3&quot;]/div[@class=&quot;col-lg-6 mb-2&quot;]/div[@class=&quot;form-floating&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>5968f7c8-10f1-4e1c-974f-ac6fcad6f039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='user[email]']</value>
      <webElementGuid>b20c1719-52bf-4807-a3ab-56a145ab9109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div[2]/form/section/div/div/div/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>e08fce37-7c55-4a56-89d1-33415717686b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>17724dbb-e590-4657-9ac0-605b851b7734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'user[email]' and @placeholder = 'Email']</value>
      <webElementGuid>d09cc159-29d1-4175-8ef9-301705fc6f03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
