<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1                                   _545fd7</name>
   <tag></tag>
   <elementGuidId>22caba20-0df3-4245-bdd5-c251c23e579e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;child_age_1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='child_age_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>423dd24e-dfce-4d96-be3e-3e8366df8f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select child_age_1</value>
      <webElementGuid>3a9a472a-1515-4dd3-817f-534cab849595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>child_age_1</value>
      <webElementGuid>0920be15-3fad-456f-b5a5-cc8a348500d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                 1 
                                                 2 
                                                 3 
                                                 4 
                                                 5 
                                                 6 
                                                 7 
                                                 8 
                                                 9 
                                                 10 
                                                 11 
                                                 12 
                                                 13 
                                                 14 
                                                 15 
                                                 16 
                                                </value>
      <webElementGuid>18a50af2-61ea-466a-8370-967fd077ec69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/div[@class=&quot;booking_data&quot;]/form[@class=&quot;book&quot;]/section[@class=&quot;booking-area padding-top-50px padding-bottom-70px&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;form-box payment-received-wrap mb-2&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;card mb-3&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;form-floating&quot;]/select[@class=&quot;form-select child_age_1&quot;]</value>
      <webElementGuid>8b859de1-220e-4322-9686-5f564d16153c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='child_age_1']</value>
      <webElementGuid>22266c13-7791-4ae9-9996-d0dd8f877fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div[2]/form/section/div/div/div/div[2]/div[2]/div[3]/div[2]/div/div/div/select</value>
      <webElementGuid>f077de48-043f-4a45-a229-404ffd838d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Childs'])[1]/following::select[1]</value>
      <webElementGuid>b263f628-81eb-401c-b997-33b89474ee8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/preceding::select[1]</value>
      <webElementGuid>571d056d-ad8b-4ebc-9a80-d7aeac795443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[4]/preceding::select[1]</value>
      <webElementGuid>06f1481b-a803-4dde-b3a0-9775ec47cac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/select</value>
      <webElementGuid>e8b7f5d0-6ccc-4f51-95b4-e9a8dd81b3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'child_age_1' and (text() = '
                                                 1 
                                                 2 
                                                 3 
                                                 4 
                                                 5 
                                                 6 
                                                 7 
                                                 8 
                                                 9 
                                                 10 
                                                 11 
                                                 12 
                                                 13 
                                                 14 
                                                 15 
                                                 16 
                                                ' or . = '
                                                 1 
                                                 2 
                                                 3 
                                                 4 
                                                 5 
                                                 6 
                                                 7 
                                                 8 
                                                 9 
                                                 10 
                                                 11 
                                                 12 
                                                 13 
                                                 14 
                                                 15 
                                                 16 
                                                ')]</value>
      <webElementGuid>bb9d2305-3886-4e5c-b3f8-d5db3d302d85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
