<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1                                   _545fd7_1</name>
   <tag></tag>
   <elementGuidId>9a168e9e-98c4-4bfe-bf8a-6cbc85988e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;child_age_2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='child_age_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b69aa8d4-9094-4faa-8f6d-f826f66b77d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select child_age_2</value>
      <webElementGuid>1ce9a7cd-718a-4bfd-bf45-763d41dbc15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>child_age_2</value>
      <webElementGuid>358855a4-3dcd-483d-818a-92e392ff7fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                 1 
                                                 2 
                                                 3 
                                                 4 
                                                 5 
                                                 6 
                                                 7 
                                                 8 
                                                 9 
                                                 10 
                                                 11 
                                                 12 
                                                 13 
                                                 14 
                                                 15 
                                                 16 
                                                </value>
      <webElementGuid>5fc779a6-bd5f-45b6-9dd6-5680946b8867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/div[@class=&quot;booking_data&quot;]/form[@class=&quot;book&quot;]/section[@class=&quot;booking-area padding-top-50px padding-bottom-70px&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;form-box payment-received-wrap mb-2&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;card mb-3&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;form-floating&quot;]/select[@class=&quot;form-select child_age_2&quot;]</value>
      <webElementGuid>d19e02a3-2d5f-4539-ba13-dd9eae8a1198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='child_age_2']</value>
      <webElementGuid>6c54f993-d467-4382-afcc-68e5a343a894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div[2]/form/section/div/div/div/div[2]/div[2]/div[4]/div[2]/div/div/div/select</value>
      <webElementGuid>3b38bca1-e438-4103-a15b-9c591c4298a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Childs'])[2]/following::select[1]</value>
      <webElementGuid>e64532bd-fa2a-4273-b222-76a6415c0863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[2]/preceding::select[1]</value>
      <webElementGuid>be6ec703-1560-424a-a8d0-39fa743aa8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[5]/preceding::select[1]</value>
      <webElementGuid>d9656387-d6fe-4727-b974-031c25a6017f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/select</value>
      <webElementGuid>c0face08-fa04-4f35-80d7-cdaaf1b5adf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'child_age_2' and (text() = '
                                                 1 
                                                 2 
                                                 3 
                                                 4 
                                                 5 
                                                 6 
                                                 7 
                                                 8 
                                                 9 
                                                 10 
                                                 11 
                                                 12 
                                                 13 
                                                 14 
                                                 15 
                                                 16 
                                                ' or . = '
                                                 1 
                                                 2 
                                                 3 
                                                 4 
                                                 5 
                                                 6 
                                                 7 
                                                 8 
                                                 9 
                                                 10 
                                                 11 
                                                 12 
                                                 13 
                                                 14 
                                                 15 
                                                 16 
                                                ')]</value>
      <webElementGuid>4b5338bb-b397-4866-8d83-e54c8d9794f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
