<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Country</name>
   <tag></tag>
   <elementGuidId>62ceed20-7e6c-42ce-b08b-1c48b348c785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;user[country_code]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='user[country_code]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>63ad6c2e-40e5-4a85-be47-165d0d75eef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[country_code]</value>
      <webElementGuid>506418f6-4f47-4971-840b-142bf8684c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country selectpicker w-100</value>
      <webElementGuid>c52f1137-f3d5-423c-a095-db9d2c494e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>054c2b9d-1cd8-4bed-8114-883bfb0744ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Select Country
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                            </value>
      <webElementGuid>c2c4734a-8b6e-4212-9a87-ec5eaa4b1605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/div[@class=&quot;booking_data&quot;]/form[@class=&quot;book&quot;]/section[@class=&quot;booking-area padding-top-50px padding-bottom-70px&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;form-box mb-2&quot;]/div[@class=&quot;form-content&quot;]/div[@class=&quot;contact-form-action&quot;]/div[@class=&quot;row g-3&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-floating mb-3&quot;]/div[@class=&quot;dropdown bootstrap-select country w-100 dropup&quot;]/select[@class=&quot;country selectpicker w-100&quot;]</value>
      <webElementGuid>2df97c30-5077-4f19-9020-191ea0fe96f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='user[country_code]']</value>
      <webElementGuid>551b7bda-7eae-41b7-871e-ec0f2e770ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div[2]/form/section/div/div/div/div/div[2]/div/div/div[7]/div/div/select</value>
      <webElementGuid>46c04041-ac95-4354-8a5d-cb1522e80744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Country'])[1]/following::select[1]</value>
      <webElementGuid>073ed293-5d2b-4100-8738-490c1fc0ef6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South Sudan'])[1]/following::select[1]</value>
      <webElementGuid>67354898-0bfb-4da6-b66e-9d58bd927af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[3]/preceding::select[1]</value>
      <webElementGuid>b4e53d39-95b1-423e-8f52-d6d461341161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Country'])[2]/preceding::select[1]</value>
      <webElementGuid>8e99ec76-2c8a-4941-a764-d5c9591c7163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>4b7dc9a3-51d3-4adc-a5f5-b8f56b9d68a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'user[country_code]' and (text() = '
                        Select Country
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                            ' or . = '
                        Select Country
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                                    
                        
                                            ')]</value>
      <webElementGuid>a6914011-7af7-4a22-9e91-d6110dadada6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
