<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Mr                        Miss      _9f97ff_1</name>
   <tag></tag>
   <elementGuidId>70c515c5-a39f-4af1-9fe4-9764994f6b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;title_2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='title_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87d6df3f-8909-4598-bdbe-dd14fc2c5b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title_2</value>
      <webElementGuid>d925be83-3051-415a-9944-9e016a848a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>4b6a510a-22d3-495c-b462-867887f178fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Mr
                        Miss
                        Mrs
                         </value>
      <webElementGuid>032a73ef-57db-4459-96ed-144ee33c33e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/div[@class=&quot;booking_data&quot;]/form[@class=&quot;book&quot;]/section[@class=&quot;booking-area padding-top-50px padding-bottom-70px&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;form-box payment-received-wrap mb-2&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;card mb-3&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row g-2&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;form-floating&quot;]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>8a21b49f-505f-4e17-bc97-794d91d1b0c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='title_2']</value>
      <webElementGuid>909f71e8-46d9-48ba-9c18-6373b92dac76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/div[2]/form/section/div/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>7724226f-e22c-4378-b080-670bbe873722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adult'])[2]/following::select[1]</value>
      <webElementGuid>24fd0bf8-f127-4e16-98cf-4d9394adf94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[2]/preceding::select[1]</value>
      <webElementGuid>91eed681-3748-49c5-8405-40e4ce368605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[3]/preceding::select[1]</value>
      <webElementGuid>d435f710-e3f0-4dfe-9d4d-8b942d11ec13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>bfe4caae-ebe8-47b0-a3e2-4fd53be63838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'title_2' and (text() = '
                         Mr
                        Miss
                        Mrs
                         ' or . = '
                         Mr
                        Miss
                        Mrs
                         ')]</value>
      <webElementGuid>6466e304-989d-4123-95c7-cf56bfb55a60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
